version: "3"
services:
  apache:
    build: docker/apache
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
  db:
    image: mariadb:11.1.3
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
